/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:345c5d19-2238-476d-a5e5-905657ce1a27",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9FsPMEzLq",
    "aws_user_pools_web_client_id": "4lhfacbgaghg71s9jr8r0nmod",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "gurshacb4b2928c96a45f992e96ed3bdfa5415121835-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
